### ISSUE TITLE
Issue in android64

### ISSUE THREAD

**Issue by LumerGD120** [OmgRod/Garage-Plus#5]
The icon kit broke when "Mod options" is turned on

![Screenshot_2024-08-11-08-12-49-09.jpg](https://github.com/user-attachments/assets/250efa38-1276-42f0-b7f3-95f5ffbd2063)

Please fix this, that would be great.

**Comment by OmgRod** [comment]
Hi. I don't seem to be experiencing these issues on my android64 device. Can you please send a list of your mods? Thanks!

**Comment by LumerGD120** [comment]
> Hi. I don't seem to be experiencing these issues on my android64 device. Can you please send a list of your mods? Thanks!

Sure here it is.

![Screenshot_2024-08-11-18-22-13-41_73932565f5d18c5d7f2b58eb6d5de17f.jpg](https://github.com/user-attachments/assets/7dbb5842-e566-4010-975a-8cc834391609)

![Screenshot_2024-08-11-18-22-06-46_73932565f5d18c5d7f2b58eb6d5de17f.jpg](https://github.com/user-attachments/assets/4a165aa7-1e8b-4f69-be6a-bdd88afd34c4)

![Screenshot_2024-08-11-18-21-45-04.jpg](https://github.com/user-attachments/assets/abfd72be-6163-49c8-81b8-4597c49297b8)

![Screenshot_2024-08-11-18-22-00-55.jpg](https://github.com/user-attachments/assets/29b62ede-0828-4020-9530-53c6c82ed01e)

![Screenshot_2024-08-11-18-20-47-65.jpg](https://github.com/user-attachments/assets/73d8ae1f-2644-4e7f-827f-b171ef332e37)

![Screenshot_2024-08-11-18-21-06-50.jpg](https://github.com/user-attachments/assets/08062cf7-2a84-41a6-a3f8-c01b![Screenshot_2024-08-11-18-20-10-23.jpg](https://github.com/user-attachments/assets/0c0a678b-f898-4c6e-b606-c0f381a1ba37)

s://github.com/user-attachments/assets/8fd4bb74-5677-4056-9be9-1f55![Screenshot_2024-08-11-18-22-17-66_73932565f5d18c5d7f2b58eb6d5de17f.jpg](https://github.com/user-attachments/assets/0742b311-2481-480b-a18d-e1489365817f)

_2024-08-11-18-22-17-66_73932565f5d18c5d7f2b58eb6d5de17f.jpg …]()

![Screenshot_2024-08-11-18-22-21-98_73932565f5d18c5d7f2b58eb6d5de17f.jpg](https://github.com/user-attachments/assets/b0de9e8f-eb44-455b-8301-aa20c140a3e6)

**Comment by LumerGD120** [comment]
> Hi. I don't seem to be experiencing these issues on my android64 device. Can you please send a list of your mods? Thanks!

Sure here it is

![Screenshot_2024-08-11-18-20-10-23.jpg](https://github.com/user-attachments/assets/6d8c0d29-1c47-4176-ba26-446c1a5b4bf7)

![Screenshot_2024-08-11-18-20-47-65.jpg](https://github.com/user-attachments/assets/ba2e79a4-b693-4362-ab1d-65b93170f665)

![Screenshot_2024-08-11-18-21-06-50.jpg](https://github.com/user-attachments/assets/899751ff-37f6-47e8-b15c-dfe23c6880d5)

![Screenshot_2024-08-11-18-21-27-67.jpg](https://github.com/user-attachments/assets/19bcb5b9-593d-4171-ab5c-1ec756b75a5f)

![Screenshot_2024-08-11-18-21-45-04.jpg](https://github.com/user-attachments/assets/5bc7b4d4-f75f-4191-9bdb-c2b9b3b2281b)

![Screenshot_2024-08-11-18-22-00-55.jpg](https://github.com/user-attachments/assets/4a346058-c8a8-4fb7-b269-8012cdd02d13)

![Screenshot_2024-08-11-18-22-06-46_73932565f5d18c5d7f2b58eb6d5de17f.jpg](https://github.com/user-attachments/assets/51c2d894-3be5-4551-ae66-3cca2e3b06de)

![Screenshot_2024-08-11-18-22-13-41_73932565f5d18c5d7f2b58eb6d5de17f.jpg](https://github.com/user-attachments/assets/acccb5fa-93d9-4151-b60a-f33193b12827)

![Screenshot_2024-08-11-18-22-17-66_73932565f5d18c5d7f2b58eb6d5de17f.jpg](https://github.com/user-attachments/assets/f4161713-501e-482d-a006-b1b3a6203329)

![Screenshot_2024-08-11-18-22-21-98_73932565f5d18c5d7f2b58eb6d5de17f.jpg](https://github.com/user-attachments/assets/7350c38c-1812-441a-b45a-825ab55adb7b)
